show databases;
use company_2025;
show tables;
use infs_zawackit;

#zadanie 1
show create table pracownik;


CREATE TABLE CLIENT AS
SELECT * FROM company_2025.CLIENT;

CREATE TABLE `ORDER` AS
SELECT * FROM company_2025.ORDER;

CREATE TABLE EMPLOYEE AS
SELECT * FROM company_2025.EMPLOYEE;

#wypisanie rekordow
SELECT * FROM `ORDER`;
DESC `ORDER`;
SELECT * FROM `ORDER` WHERE ORDER_STATUS = 5;

SELECT ORDER_ID , ORDER_STATUS FROM `ORDER` 
WHERE CLIENT_ID = 1 OR CLIENT_ID = 3 OR CLIENT_ID = 5;

#zadanie 2
SELECT * FROM EMPLOYEE;
SELECT * FROM CLIENT;

SELECT * FROM EMPLOYEE WHERE FIRST_NAME = 'Agnieszka' AND pensja = 3900.00;
SELECT * FROM EMPLOYEE WHERE pensja>=5000 and pensja<=7000;
SELECT SHORT_NAME FROM CLIENT WHERE SHORT_NAME LIKE 'eco%' and IS_COMPANY=1;

# % - DOWOLNY CIAG ZNAKOW
# _ - DOKLADNIE JEDEN DOWOLNY ZNAK

#zadanie 3
#pkt1
SELECT * FROM `ORDER` WHERE MONTH(ORDER_DATE) IN (6,7);

#pkt2
SELECT TAX_IDENTIFIER FROM CLIENT 
WHERE TAX_IDENTIFIER is not NULL
ORDER BY SHORT_NAME;

# != rozny od
# <> rozny od

#pkt3
SELECT * FROM EMPLOYEE ORDER BY BIRTH_DATE limit 5;

#od tylu
SELECT * FROM EMPLOYEE ORDER BY BIRTH_DATE desc;

#zadanie 4 
SELECT * FROM EMPLOYEE;

SELECT distinct(FIRST_NAME) FROM EMPLOYEE;

SELECT concat(FIRST_NAME,' - ', LAST_NAME) from EMPLOYEE WHERE LAST_NAME LIKE 'Ko%';

SELECT concat(LAST_NAME,' ', pensja) from EMPLOYEE 
WHERE YEAR(DATE_OF_EMPLOYMENT) between 2010 and 2014;

#zadanie 5
SELECT pensja, pensja*0.75, pensja*0.25 FROM EMPLOYEE;

SELECT * FROM CLIENT WHERE TAX_IDENTIFIER IS NULL;

SELECT * FROM CLIENT WHERE SHORT_NAME LIKE 'K%' and SHORT_NAME LIKE '%ski'
ORDER BY SHORT_NAME DESC;