select sum(AMOUNT) from INVENTORY;
show databases;
use infs_zawackit;
show tables;

select * FROM EMPLOYEE;

select concat(FIRST_NAME, LAST_NAME)
FROM EMPLOYEE;


#1
select avg(pensja) from EMPLOYEE;

SELECT JOB_POSITION_ID, AVG(pensja), COUNT(*)
FROM EMPLOYEE
GROUP BY JOB_POSITION_ID;

SELECT DEPARTMENT_ID, (2025-AVG(YEAR(BIRTH_DATE)))
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID;

#2
SELECT sum(pensja) from EMPLOYEE
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID DESC;

SELECT JOB_POSITION_ID, AVG(pensja), count(*)
FROM EMPLOYEE WHERE JOB_POSITION_ID < 3
GROUP BY JOB_POSITION_ID
HAVING count(*) >= 3 AND AVG(PENSJA) > 3000;

SELECT DEPARTMENT_ID, count(distinct pensja) FROM EMPLOYEE
group by DEPARTMENT_ID
HAVING count(distinct pensja)
order by count(distinct pensja) ASC;

select * from EMPLOYEE;
#3
CREATE TABLE DEPARTMENT AS
SELECT * FROM company_2025.DEPARTMENT;

CREATE TABLE JOB_POSITION AS
SELECT * FROM company_2025.JOB_POSITION;

#pkt2
SELECT DEPARTMENT.DEPARTMENT_NAME, COUNT(EMPLOYEE.EMPLOYEE_NAME) from DEPARTMENT
JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID
group by DEPARTMENT.DEPARTMENT_NAME;

#pk3
SELECT DEPARTMENT.DEPARTMENT_NAME, concat(EMPLOYEE.FIRST_NAME, ' ', EMPLOYEE.LAST_NAME) from DEPARTMENT
JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

#zad4
#PKT1
SELECT DEPARTMENT.DEPARTMENT_NAME, EMPLOYEE.LAST_NAME, YEAR(EMPLOYEE.BIRTH_DATE) from DEPARTMENT
JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID
WHERE YEAR(EMPLOYEE.BIRTH_DATE) between 1990 and 2000;

#PKT2
SELECT DEPARTMENT.DEPARTMENT_NAME, EMPLOYEE.FIRST_NAME, EMPLOYEE.LAST_NAME FROM DEPARTMENT
JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID
WHERE DEPARTMENT_NAME='Magazyn'
ORDER BY BIRTH_DATE
LIMIT 5;

#pkt 3
SELECT c1.SHORT_NAME, c2.SHORT_NAME
FROM CLIENT c1
JOIN CLIENT c2 ON c1.CLIENT_ID = c2.CLIENT_ID + 5;

#zadanie 5 pkt 1
SELECT JOB_POSITION_ID, AVG(PENSJA)
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE d.DEPARTMENT_NAME NOT IN ('IT', 'HR')
GROUP BY JOB_POSITION_ID
HAVING COUNT(*) > 3;

