show databases;
use infs_zawackit;
show tables;

#zad 1
select * from CLIENT;
SELECT * FROM CLIENT_ADDRESS;

select * from ADDRESS_TYPE
limit 5;

#pkt 1.1
select c.FULL_NAME, STREET, substr(STREET,5,5) as 'pierwsze 5 znaków ulicy'  from CLIENT c
inner join CLIENT_ADDRESS ca on c.CLIENT_ID = ca.CLIENT_ID;

#pkt 1.2
select c.SHORT_NAME, adt.ADDRESS_TYPE_NAME from CLIENT c
left join CLIENT_ADDRESS ca on c.CLIENT_ID = ca.CLIENT_ID
left join ADDRESS_TYPE adt on ca.ADDRESS_ID = adt.ADDRESS_TYPE_ID;

#pkt 1.3
select * from PRODUCT;
SELECT * FROM `ORDER`;
SELECT * FROM ORDER_STATUS;

SELECT p.PRODUCT_NAME, c.CATEGORY_NAME, substr(PRODUCT_NAME,1,3) as 'pierwsze 3 znaki produktu' from PRODUCT p
inner join CATEGORY c on p.CATEGORY_ID = c.CATEGORY_ID;

#pkt 1.4
select p.PRODUCT_NAME, `DESCRIPTION` from PRODUCT p; ###

#zad 2.1
SELECT FULL_NAME, o.ORDER_NUMBER, o.ORDER_DATE, DATEDIFF(CURDATE(), o.ORDER_DATE) as 'ilość dni od zakupu' FROM CLIENT c
INNER JOIN `ORDER` o on c.CLIENT_ID = o.CLIENT_ID;

#2.2
SELECT ORDER_DATE, adddate(ORDER_DATE, INTERVAL 14 DAY) as 'data zapłaty' FROM `ORDER` o
INNER JOIN ORDER_STATUS os on os.STATUS_ID = o.ORDER_STATUS
WHERE STATUS_NAME != 'Zwrocone' or 'Zamkniete';


#2.3
SELECT FIRST_NAME, LAST_NAME, DATE_OF_EMPLOYMENT, d.DEPARTMENT_NAME FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d on e.DEPARTMENT_ID = d.DEPARTMENT_ID;

#2.4
SELECT * FROM CLIENT;

SELECT * FROM `ORDER`
WHERE CLIENT_ID = 1
ORDER BY ORDER_DATE asc
LIMIT 1;


select datediff(MIN(ORDER_DATE), MAX(ORDER_DATE)) FROM CLIENT c
INNER JOIN `ORDER` o on o.CLIENT_ID = c.CLIENT_ID
group by c.CLIENT_ID;




#ZAD 3.1
SELECT * FROM CLIENT_ADDRESS;

SELECT SHORT_NAME, concat(STREET,', ',CITY) FROM CLIENT c
INNER JOIN CLIENT_ADDRESS ca on ca.CLIENT_ID = c.CLIENT_ID;

#zad 3.2
SELECT CITY, left(POSTAL_CODE,2) FROM CLIENT_ADDRESS;

#ZAD 3.3
SELECT concat(LAST_NAME,' ', FIRST_NAME,', ', DEPARTMENT_ID,', ', DATE_OF_EMPLOYMENT) FROM EMPLOYEE;
SELECT * FROM EMPLOYEE;

#ZAD 3.4
SELECT * FROM `ORDER`;


SELECT concat(FULL_NAME,' - ',SHORT_NAME), group_concat(ORDER_NUMBER) SEPARATOR ', ') as 'aha' FROM CLIENT c
INNER JOIN `ORDER` o on o.CLIENT_ID = c.CLIENT_ID
GROUP BY c.CLIENT_ID; ##

SELECT  group_concat((CLIENT_ID,3) SEPARATOR ', ') as 'aha' FROM CLIENT c
GROUP BY c.CLIENT_ID; ##

#ZAD 3.5

#ZAD 4.1
SELECT 
DATE_FORMAT(ORDER_DATE, '%d-%m-%Y'),
DATE_FORMAT(ORDER_DATE, '%Y - %u'),
DATE_FORMAT(ORDER_DATE, '%Y - %j'),
DATE_FORMAT(ORDER_DATE, '%M %d %Y')
FROM `ORDER`

















